spring:
  application:
    name: spring-demo
  profiles:
    active: dev
  jackson:
    timezone: GMT+8
  redis:
    database: 0
    host: 192.168.0.101
    port: 6379
    password: password
    timeout: 10000 # 连接超时时间（毫秒）
    block-when-exhausted: true
    jedis:
      pool:
        max-wait: 100000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

server:
  port: 8085

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel: true
    default-fetch-size: 100
    default-statement-timeout: 30