spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: password
    hikari:
      maximum-pool-size: 50
  redis:
    host: localhost
    port: 6379
    password: password
    timeout: 1000 # 连接超时时间（毫秒）