server:
  port: 8086
  error:
    include-exception: true
    include-stacktrace: always

spring:
  application:
    name: spring-demo
  profiles:
    active: dev
  jackson:
    timezone: GMT+8
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0 # 上传数据大于该值时，内容写入文件
      max-file-size: 35MB #允许上传的单个文件最大值，-1 表示没有限制
      max-request-size: 35MB # 单次上传的总文件大小，-1 表示没有限制
  http:
    encoding:
      charset: UTF-8
      enabled: true
      fore: true

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel: true
    default-fetch-size: 100
    default-statement-timeout: 30