spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: password
    hikari:
      maximum-pool-size: 50
  redis:
    host: localhost
    port: 6379
    password: password
    timeout: 1000 # 连接超时时间（毫秒）
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 2897547167@qq.com #发送邮件的邮箱地址
    password: scjuprdgzlysdefc #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 2897547167@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8