package com.example.demo.mapper;

import com.example.demo.entity.Person;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated
     */
    List<Person> selectAll();

    @Select("select * from person where id=#{id}")
    Person get(Integer id);
}